author:
- winezero
matches:
- keyword: Amazon Web Services Web Application Firewall
  search: text
- keyword: Amazon
  search: text
name: amazon-web-services-web-application-firewall-amazon
type: webApp
version: '0.1'
