author:
- winezero
matches:
- keyword: x-amz-id-2
  search: headers
- keyword: x-amz-request-id
  search: headers
- keyword: <Error><Code>AccessDenied
- keyword: <title>Grey Wizard
name: amazon-web-services-web-application-firewall-waf
type: device
version: '0.1'
