author:
- winezero
matches:
- certainty: 50
  regex: aksb\.min\.js
  search: text
- regex: ds-aksb-a\.akamaihd\.net.aksb.min.js
  search: text
name: akamai-web-application-protector
type: webApp
version: '0.1'
