author:
- winezero
matches:
- keyword: yunsuo
  search: headers
- keyword: yunsuo_session
  search: headers
- keyword: yunsuologo
name: yunsuo-web-application-firewall-yunsuo-waf
type: webApp
version: '0.1'
