author:
- Brendan Coles <bcoles@gmail.com>
description: ACTi Web Configurator - camera web interface
matches:
- regex: <form name="frm(LOGIN|Config)" method="POST" enctype="multipart/form-data"
    action="videoconfiguration\.cgi">
- keyword: "ACTi \u76D1\u63A7\u6444\u50CF\u673A"
  search: text
- regex: <tr class="layout_footer_bgcolor">\s*<td width="776"[^>]*>\s+Copyright@2003-(20[\d]{2})
    ACTi Corporation All Rights Reserved
- keyword: ACTi Corporation All Rights Reserved
- keyword: Web Configurator
- aim: version
  regex: <title>Web Configurator - Version ([^\s]*\s?v[^<]+)</title>
name: ACTi-Web-Configurato
type: webApp
version: '0.2'
website: http://www.acti.com/home/index.asp
