author:
- winezero
matches:
- keyword: x-amz-id-2
  search: headers
- keyword: x-amz-request-id
  search: headers
- keyword: <Error><Code>AccessDenied
- keyword: <title>Grey Wizard
name: amazon_web_services_web_application_firewall_waf
type: webApp
version: '0.1'
