author:
- Brendan Coles <bcoles@gmail.com>
description: 'Aruba''s family of mobility controllers are purpose-built network infrastructure
  devices, designed from the ground up to provide secure, scalable solutions for campus
  wireless LAN, wired security, branch office deployments, and remote networking. '
matches:
- keyword: logging level warnings stm
- keyword: packet-capture-defaults tcp disable udp disable sysmsg disable other disable
- keyword: ids-policy rate-frame-type-param disassoc node-time-interval
name: Aruba-Mobility-Controller-Config-File
type: webApp
version: '0.1'
website: http://www.arubanetworks.com/products/mobility_controllers.php
