author:
- Brendan Coles <bcoles@gmail.com>
description: Basic Analysis and Security Engine (BASE) - front end for the snort IDS
  system.
matches:
- regex: thebase\.in.js
  search: text
- keyword: <!-- Basic Analysis and Security Engine (BASE) -->
- keyword: mailto:base@secureideas.net
- aim: version
  regex: <!-- Basic Analysis and Security Engine \(BASE\) ([\d\.]+ \([^\)]+\)) -->
name: BASE
type: webApp
version: '0.1'
website: http://base.secureideas.net/
