author:
- Brendan Coles <bcoles@gmail.com>
description: Enhydra Application Server
matches:
- keyword: Enhydra
  search: headers
- aim: version
  regex: ^Enhydra-MultiServer/([^\s]+)
  search: headers[server]
- aim: version
  regex: Enhydra Application Server/([^\s]+)
  search: headers[servlet-engine]
name: enhydra-application-server
type: middleware
version: '0.1'
website: http://enhydra.org/
