author:
- Brendan Coles <bcoles@gmail.com>
description: A web application framework. Projects using the framework include webmail,
  a wiki and groupware. (Mostly PHP)
matches:
- md5: b74924c612af6030729d7ac3bd0ef803
  url: themes/graphics/horde-power1.png
- keyword: horde_secret_key
  search: headers
- keyword: if (typeof(_setHordeTitle) == 'undefined' && document.title && parent.frames.horde_main)
    parent.document.title = document.title;
- keyword: /themes/graphics/horde-power1.png" alt="Powered by Horde" title="" />
- regex: '<!--   Horde Project: http://horde.org/ | IMP: http://horde.org/imp/    -->'
- keyword: '<!-- IMP: Copyright 2001-2006, The Horde Project. IMP is under the GPL.
    -->'
- keyword: <!-- This file contains any "Message Of The Day" Type information -->
- keyword: <a href="icon_browser.php?app=chora">Version Control</a><br />
- keyword: <html><body bgcolor="#aaaaaa"><a href="icon_browser.php">Application List</a><br
    /><br /><h2>Icons for My Account</h2>
- keyword: <img src="/themes/default/graphics/horde-power1.png
- keyword: <link href="/mail/mailbox.php?mailbox=INBOX" rel="Top" />
- keyword: <script language="JavaScript" type="text/javascript" src="/hunter/js/enter_key_trap.js"></script>
- keyword: Powered by </font><a href="http://www.horde.org/" TARGET=_blank>
- keyword: Powered by Horde
- keyword: title="This site is powered by The Horde Application Framework." href="http://horde.org">
- aim: version
  regex: '<!-- \$Horde: horde/config/conf.xml,v ([\d\.]+) '
- aim: version
  regex: <title>WebMail ([\d\.]+) LOGIN</title>
name: Horde-Application-Framework
type: webApp
version: '0.3'
website: http://www.horde.org/
