author:
- Andrew Horton
description: ISPConfig is a free, opensource hosting control panel
matches:
- regex: powered by <a HREF="http://www.ispconfig.org">ISPConfig</a>
- certainty: 75
  keyword: This IP address is shared. For access to the web site which you look for,
    enter its address instead of its IP.
name: ISPConfig
type: webApp
version: '0.3'
website: http://www.ispconfig.org/
