author:
- Brendan Coles <bcoles@gmail.com>
description: ManageEngine Applications Manager - monitoring software - includes server
  monitoring, application server monitoring, database monitoring, web services monitoring,
  virtualization monitoring, cloud monitoring
matches:
- keyword: <!-- This comment is for Instant Gratification to work applications.do
    -->
- keyword: <SCRIPT LANGUAGE="JavaScript1.2" SRC="/template/appmanager.js"></SCRIPT>
- keyword: <title>Applications Manager Login Screen</title>
- aim: version
  regex: '<td>Applications Manager \((Build No:[\d]+)\) &nbsp;&nbsp;&nbsp;&nbsp;Number
    of Monitor\(s\) : '
- md5: 4454cf4db9355b0e26b98cc354213c56
  url: images/am_logo.gif
name: ManageEngine-Applications-Manager
type: webApp
version: '0.1'
website: http://www.manageengine.com/products/applications_manager/
