author:
- Brendan Coles <bcoles@gmail.com>
description: 'Mission Control Application Shield functions as a Web Application Firewall
  (WAF) and offers the following features: SSL offloading, single sign-on, high availability
  through system redundancy, backend server failover and load balancing, session fixation,
  cookie encryption, different methods of authentication (Radius, NTLM/Kerberos, LDAP),
  header and form validation and a live log viewer'
matches:
- keyword: <img id="logo" src="/srm-error-pages/images/logo.gif" alt="mission control
    application shield" ></td><td><p class="notification">Notification</p></td>
- regex: ^Mission Control Application Shield$
  search: headers[server]
name: Mission-Control-Application-Shield
type: webApp
version: '0.1'
website: http://www.open.ch/1_1_2_1.html
