author:
- winezero
matches:
- offset: 1
  regex: 'Oracle[- ]Application[- ]Server(?: Containers for J2EE)?(?:[- ](\d[\da-z..]+))?'
  search: headers[server]
name: oracle_application_server
type: webApp
version: '0.1'
