author:
- Brendan Coles <bcoles@gmail.com>
description: Oracle iAS (Internet Application Server)
matches:
- aim: version
  regex: ^Oracle9iAS/([^\s]+)
  search: headers[server]
- aim: version
  regex: ^Oracle9iAS \(([^\s^\)]+)\)
  search: headers[server]
- aim: module
  regex: ^Oracle9iAS.+ (Oracle9iAS-Web-Cache/[^\s]+)
  search: headers[server]
name: Oracle-Internet-Application-Server
type: webApp
version: '0.1'
website: http://www.oracle.com/technetwork/middleware/ias/index.html
