author:
- Brendan Coles <bcoles@gmail.com>
description: Oracle Application Server - superseded by Oracle iAS (Internet Application
  Server)
matches:
- keyword: Oracle Application Server
  search: text
- keyword: Oracle-Application-Server
  search: headers
- aim: module
  regex: ^Oracle[ -]Application[ -]Server.+ (OracleAS-Web-Cache-1[01]g/[^\s]+)
  search: headers[server]
- regex: ^Oracle-Application-Server-(1[01]g)
  search: headers[server]
- aim: version
  regex: ^Oracle Application Server/1[01]g \(([^\s^\)]+)\)
  search: headers[server]
- aim: version
  regex: ^Oracle-Application-Server-1[01]g/([^\s]+)
  search: headers[server]
- offset: 1
  regex: 'Oracle[- ]Application[- ]Server(?: Containers for J2EE)?(?:[- ](\d[\da-z..]+))?'
  search: headers[server]
name: oracle-application-server
type: middleware
version: '0.1'
website: http://www.oracle.com/technetwork/middleware/ias/index.html
