author:
- winezero
matches:
- keyword: X-Mapping-
  search: headers
  status: '403'
- keyword: X-Mapping-
  search: headers
  status: '500'
name: stingray-application-firewall-waf
type: webApp
version: '0.1'
