author:
- winezero
matches:
- regex: swagger-ui[-\w]+.(css|js)
- keyword: <div id="swagger-ui"></div>
- keyword: <title>Swagger UI</title>
- keyword: Workaround for https://github.com/swagger-api
name: swagger-ui
type: other
version: '0.2'
