author:
- Brendan Coles <bcoles@gmail.com>
description: Symantec Client Security
matches:
- keyword: <!-- Symantec Client Security Web Based Installation -->
- certainty: 75
  regex: <META NAME="Copyright" Content="Copyright (20[\d]{2}) Symantec Corporation">
name: Symantec-Client-Security
type: webApp
version: '0.1'
website: http://www.symantec.com
