author:
- Brendan Coles <bcoles@gmail.com>
description: The Warcraft 3 mod for AMX-Mod-X for Half-Life uses a config file which
  contains mySQL username, password, server, database name, table name. This plugin
  grabs the mySQL username, password and server.
matches:
- keyword: // Radius to give XP to teammates near where the special objective is completed
    (rescued hosties, bomb planted, killed vip, vip escaped, default is 750)
name: warcraft-3-frozen-throne-config-file
type: webApp
version: '0.1'
