author:
- Brendan Coles <bcoles@gmail.com>
- Andrew Horton
description: WebHare Application Portal - Enterprise Content Management - The flexible
  design of WebHare AP allows for complex web applications completely tailored to
  build support for an intranet or website as well as a separate product line.
matches:
- regex: ^WebHare Application Portal
  search: headers[server]
- aim: version
  regex: ^WebHare Application Portal v([\d\.]+) Webserver$
  search: headers[server]
name: WebHare-Application-Portal
type: webApp
version: '0.2'
website: http://www.b-lex.nl/
