author:
- winezero
matches:
- keyword: yunsuo
  search: headers
- keyword: yunsuo_session
  search: headers
- keyword: \"yunsuologo
name: yunsuo_web_application_firewall_(yunsuo)_waf
type: webApp
version: '0.1'
